import { BarGraph } from "../components/charts/Bar"
import { LineGraph } from "../components/charts/Line"
import Card from "../components/Card"
import { PieGraph } from "../components/charts/Pie"
import { useState } from "react"


const Visualization = () => {

  const [currentIndex, setCurrentIndex] = useState(null)
  return (
    <div>
    <section className='max-container'>
      <h1 className='head-text'>
        Total Weight {" "}
        <span className='blue-gradient_text font-semibold drop-shadow'>
          {" "}
          Visualization
        </span>{" "}
        👋
      </h1>

      <div className='mt-5 flex flex-col gap-3 text-slate-500'>
        <p>
          This graph shows the overall weight of waste generated by each building based on our dataset. <br/> From this graph, we can see that there is a significant amount of recycling work that needs to be done, especially for the <span className='blue-gradient_text font-semibold drop-shadow'>
          {" "}
          Benson Center!
        </span>
          </p>
          <BarGraph setCurrentIndex={setCurrentIndex} />
          <p >
        {currentIndex == null ?  <p><span className='blue-gradient_text font-semibold drop-shadow'>
       
          Please hover or click to check more information ✨
        </span><br/>We analyzed the sorting accuracy for each waste category.</p> : <Card currentIndex={currentIndex} />}
      </p>
      </div>

      <div className='py-10 flex flex-col text-slate-500'>
          <h3 className='subhead-text'>Overall Waste Distribution</h3>
          <div className='py-10 flex flex-row'>
            <div >
               <PieGraph />
            </div>
           
             <p>
         This pie chart shows the weight distribution of waste for each building in terms of compost, landfill, and recycling. From the observation, we can see that most of the waste comes from<span className='blue-gradient_text font-semibold drop-shadow'>
          {" "}
           compost and recycling.
              </span></p>
            
          </div>
       <p>
            Even though Compost and Landfill is the main source of trash, however, based on the sorted correction above, they have a very low sorted correctness, which means, most people at Santa Clara University throw them into an not correct stream.<br/>

Effective waste recycling at universities is crucial not only for reducing the environmental impact but also for fostering a culture of sustainability among students. By implementing robust recycling programs, universities can significantly decrease landfill waste, lower carbon footprints, and conserve natural resources. Moreover, these initiatives serve as practical educational tools, shaping students' mindsets towards responsible consumption and environmental stewardship. Encouraging good recycling habits on campus instills a sense of accountability and environmental consciousness that students can carry into their future personal and professional lives.
              
            </p>
      </div>

      <hr className='border-slate-200' />
    </section>
    </div>
  )
}

export default Visualization
